// PM2 ecosystem config for direct deployment
module.exports = {
  apps: [
    {
      name: 'rivaleye-api',
      script: 'pnpm',
      args: '--filter @rivaleye/api start',
      cwd: '/home/faizan514pathan/rivaleye-v3',
      watch: false,
      restart_delay: 4000,
      error_file: './logs/rivaleye-api-err.log',
      out_file: './logs/rivaleye-api-out.log',
      env: { NODE_ENV: 'production' },
      max_memory_restart: '1G',
    },
    {
      name: 'rivaleye-landing',
      script: 'npx',
      args: 'http-server packages/landing/dist -p 3000 -c-1',
      cwd: '/home/faizan514pathan/rivaleye-v3',
      watch: false,
      restart_delay: 4000,
      error_file: './logs/rivaleye-landing-err.log',
      out_file: './logs/rivaleye-landing-out.log',
      env: { NODE_ENV: 'production' },
    },
    {
      name: 'rivaleye-web',
      script: 'npx',
      args: 'serve -s packages/web/dist -l 4004',
      cwd: '/home/faizan514pathan/rivaleye-v3',
      watch: false,
      restart_delay: 4000,
      error_file: './logs/rivaleye-web-err.log',
      out_file: './logs/rivaleye-web-out.log',
      env: { NODE_ENV: 'production' },
    },
    {
      name: 'rivaleye-scrape',
      script: 'pnpm',
      args: '--filter @rivaleye/worker start:scrape',
      cwd: '/home/faizan514pathan/rivaleye-v3',
      watch: false,
      restart_delay: 4000,
      error_file: './logs/rivaleye-scrape-err.log',
      out_file: './logs/rivaleye-scrape-out.log',
      env: { NODE_ENV: 'production' },
      max_memory_restart: '1G',
    },
    {
      name: 'rivaleye-synth',
      script: 'pnpm',
      args: '--filter @rivaleye/worker start:synth',
      cwd: '/home/faizan514pathan/rivaleye-v3',
      watch: false,
      restart_delay: 4000,
      error_file: './logs/rivaleye-synth-err.log',
      out_file: './logs/rivaleye-synth-out.log',
      env: { NODE_ENV: 'production' },
      max_memory_restart: '1500M',
    }
  ]
};
