export const PERMISSIONS = {
  COMPETITORS_VIEW: "COMPETITORS_VIEW",
  COMPETITORS_MANAGE: "COMPETITORS_MANAGE",
  REPORTS_VIEW: "REPORTS_VIEW",
  REPORTS_CREATE: "REPORTS_CREATE",
  RADAR_VIEW: "RADAR_VIEW",
  DASHBOARD_VIEW: "DASHBOARD_VIEW",
} as const;

export type Permission = keyof typeof PERMISSIONS;
