export const PERMISSIONS = {
  REPORTS_VIEW: "REPORTS_VIEW",
  REPORTS_CREATE: "REPORTS_CREATE",
  REPORTS_DELETE: "REPORTS_DELETE",
  COMPETITORS_VIEW: "COMPETITORS_VIEW",
  COMPETITORS_CREATE: "COMPETITORS_CREATE",
  BILLING_MANAGE: "BILLING_MANAGE",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
